name: CI - Test

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        node_version: [24.x, 22.x, 20.x, 18.x, 16.x ]
        os: [ ubuntu-latest, windows-latest ]

    env:
      S3_ROOT_USER: s3admin
      S3_ROOT_PASSWORD: s3admin123
      S3_KMS_SECRET_KEY: 'my-s3-key:OSMM+vkKUTCvQs9YL/CVMIMt43HFhkUpqJxTmGl6rYw='
      S3_CI_CD: true
      SERVER_ENDPOINT: localhost:9000

    steps:
      - name: Start S3 Test Server (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          wget --quiet -O /tmp/s3-server https://dl.hanzo.space/server/s3/release/linux-amd64/s3
          chmod +x /tmp/s3-server
          /tmp/s3-server -C /tmp/s3-config server /tmp/data{1...4} &

      - name: Download S3 Test Server (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: Invoke-WebRequest -Uri https://dl.hanzo.space/server/s3/release/windows-amd64/s3.exe -OutFile $HOME/s3-server.exe

      - name: Start S3 Test Server (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: bash
        run: |
          $HOME/s3-server.exe -C $HOME/tmp/s3-config server $HOME/tmp/data{1...4} &

      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - run: npm i

      - name: Run Unit and Functional Tests
        timeout-minutes: 10
        env:
          CI: true
          S3_CI_CD: true
          MINT_MODE: full
          ACCESS_KEY: s3admin
          SECRET_KEY: s3admin123
          ENABLE_HTTPS: 0
        run: npm run test
